name: time_news_app
description: "A time news app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  dio: ^5.5.0+1
  mocktail: ^1.0.4
  sqflite: ^2.3.3+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  faker: ^2.1.0
  sqflite_common_ffi: ^2.3.3
  bloc_test: ^9.1.7


flutter:
  uses-material-design: true

  assets:
    - .env
